# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
StyLua = "JohnnyMorganz/StyLua@2.3.0"
selene = "Kampfkarren/selene@0.29.0"
wally = "UpliftGames/wally@0.3.2"
rojo = "rojo-rbx/rojo@7.6.0"
